#-------------------------------
# Site Settings
title: Privacy Encrypt
logo: "/images/logo.svg" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/logo-dark.png"
description: Baleon is a stylish and multifunctional theme for Jekyll
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Elements'
      url: '/elements/'


# Call to action button
cta_button:
  enable: true
  cta_button_link: "/cyberfolio/contact/"
  cta_button_text: Say Hello!


#-------------------------------
# Author Settings
author:
  author_intro: Hey, I’m Ty Fisher
  author_name: Ty Fisher
  author_role: Cybersecurity Specialist | SOC Analyst
  author_avatar: /images/01.jpg


#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: Mastering Cybersecurity <em>Interactive Labs,</em> <em>Security Insights,</em> <em>Defense Strategies</em>. # You can add an 'em' element to highlight text.
  sidebar_description: Welcome to a journey of discovery and growth in the ever-evolving field of cybersecurity. True understanding lies not in simply acquiring knowledge, but in sharing it to empower and inspire others. This repository is designed to be more than a collection of insights—it’s a resource and a guide for those seeking to learn, practice, and excel, fostering a collaborative path toward mastery.

#-------------------------------
# Social Links
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
- {icon: "fa-brands fa-spotify", name: "Spotify", link: "https://spotify.com"}
- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Cyber Labs <em>Showcase</em> # You can add an 'em' element to highlight text.
  projects_description: Engage in hands-on practice through guided walkthroughs that replicate real-world cybersecurity scenarios. Each exercise is carefully designed to immerse you in the tools, techniques, and challenges faced by professionals. These simulations help you develop technical expertise, sharpen problem-solving skills, and build the confidence to navigate the ever-changing cybersecurity landscape.


#-------------------------------
# Testimonials Settings
testimonials:
  enable: true
  testimonials_title: SOC Analyst <em>Tool Kit</em> # You can add an 'em' element to highlight text.
  testimonials_description: These are just a few of the powerful tools leveraged as a SOC analyst. Staying one step ahead of the adversary is the name of the game, and mastering these technologies ensures we’re always ready to defend against evolving threats.
testimonial-items:
  - name: Amelia Jones
    image: "/images/client-1.jpg"
    designation : Network Engineer
    content : This soc analyst is an expert in his field. His ability to understand the needs of clients and create solutions that satisfy them is astounding.

  - name: Ethan Robinson
    image: "/images/client-2.jpg"
    designation : Blockchain Developer
    content : Ty is a true visionary in the field of cyber security. His ability to think outside the box and push boundaries is what sets him apart from the rest.

  - name: Matthew Garcia
    image: "/images/client-3.jpg"
    designation : IT Support Specialist
    content : I cannot recommend this IT security consultant enough. Their ideas were simple to execute, yet complex enough to substantially improve our security posture.


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest <em>Articles</em> & <em>Publications</em> # You can add an 'em' element to highlight text.
  blog_description: Your portal to in-depth articles exploring key cybersecurity topics, emerging trends, and evolving threats. Each article is paired with a hands-on walkthrough lab, allowing you to apply concepts in real-world scenarios. By combining detailed analysis with practical exercises, these resources are designed to deepen your understanding and equip you with the skills needed to confidently navigate the ever-changing cybersecurity landscape.
#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Questions? <em>Answers</em>. # You can add an 'em' element to highlight text.
  faq_description: Find solutions to common queries here.

faq_items:
  - title: What are your main areas of expertise in cyber security?
    description: My specialization includes threat detection, incident response, and vulnerability assessment, as well as researching and testing security measures to protect systems and data.

  - title: Can you provide examples of your work?
    description: Yes, on my website, you can find a portfolio showcasing examples of my cybersecurity projects, interactive labs, and certifications aligned with industry standards.

  - title: What is your experience with various hardware and software?
    description: I have extensive experience working with various systems, including network infrastructures, servers, endpoint devices, security software, and hardware solutions.

  - title: What specific tools do you use in your working environment?
    description: In my working environment, I utilize a wide range of cybersecurity tools, including SIEM systems (such as Splunk and ELK Stack), network scanners (like Nmap and Wireshark), vulnerability assessment tools (such as Nessus and OpenVAS), and endpoint security solutions (like CrowdStrike and SentinelOne), to name just a few.

  - title: What certifications and qualifications do you bring to the table?
    description: I hold certifications in Google Cybersecurity, CompTIA Security+, CySA+, Cloud Security, and AWS. In addition, I have a Master's degree in Education, which complements my ability to communicate complex concepts effectively. As a lifelong learner, I am continuously expanding my expertise and look forward to adding more certifications and skills to this growing list.

  - title: How can I contact you to discuss my project?
    description: You can contact me through the contact form on my website or directly via email. I'm always open to new projects and ready to discuss your security needs.


#-------------------------------
# Gallery Settings
gallery:
  enable: true
  gallery_title: Certifications <em>My Path To Cyber Enlightenment</em> # You can add an 'em' element to highlight text.
  gallery_description: The certifications I’ve earned reflect my dedication to mastering cybersecurity and my commitment to lifelong learning. Each marks a step forward, showcasing my knowledge and determination to stay ahead in this ever-changing field. This is just the beginning—I’m driven to expand this list, embrace new challenges, and grow with the dynamic world of cybersecurity.
  gallery_caption: "Certifications: Milestones of mastery, stepping stones to the future."
gallery_images:
  - alt: 'abstract-a'
    url: '/images/97.jpg'
  - alt: 'abstract-b'
    url: '/images/94.jpg'
  - alt: 'abstract-c'
    url: '/images/96.jpg'
  - alt: 'abstract-d'
    url: '/images/79.jpg'
  - alt: 'abstract-e'
    url: '/images/89.jpg'
  - alt: 'abstract-f'
    url: '/images/87.jpg'
  - alt: 'abstract-g'
    url: '/images/85.jpg'
  - alt: 'abstract-h'
    url: '/images/88.jpg'
  - alt: 'abstract-i'
    url: '/images/92.jpg'
  - alt: 'abstract-j'
    url: '/images/74.jpg'
  - alt: 'abstract-k'
    url: '/images/73.jpg'
  - alt: 'abstract-l'
    url: '/images/82.jpg'
  - alt: 'abstract-m'
    url: '/images/83.jpg'
  - alt: 'abstract-n'
    url: '/images/90.jpg'
  - alt: 'abstract-o'
    url: '/images/95.jpg' 

# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Subscribe to Our <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Join now and stay ahead in cybersecurity. Because your security matters!
  mailchimp_identifier: github.us10.list-manage.com/subscribe/post?u=21c208292da350e84bd383e0b&id=2adf53acb3

  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: f/xvgojkyv # Add your form_id
  description: Have a question about cybersecurity, need expert guidance, or want to discuss potential collaboration? I’m always open to connecting with businesses and professionals who are passionate about securing their digital assets. Whether it’s addressing your security challenges, exploring innovative solutions, or simply exchanging ideas, don’t hesitate to reach out. Let’s work together to build a safer digital world!

# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: privacy-encrypt # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-YX3RPSSSB2 # Add your GA Tracking Id
