#-------------------------------
# Site Settings
title: Baleon
logo: "/images/logo.svg" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/logo-dark.svg"
description: Baleon is a stylish and multifunctional theme for Jekyll
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Elements'
      url: '/elements/'


# Call to action button
cta_button:
  enable: true
  cta_button_link: "/cyberfolio/contact/"
  cta_button_text: Say Hello!


#-------------------------------
# Author Settings
author:
  author_intro: Hey, I’m Ty Fisher
  author_name: Ty Fisher
  author_role: Cybersecurity Specialist | SOC Analyst
  author_avatar: /images/01.jpg


#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: One Stop Daily <em>Interactive Labs,</em> <em>Security Insights,</em> <em>Cyber Defense Strategies</em>. # You can add an 'em' element to highlight text.
  sidebar_description: Welcome to a unique world of cybersecurity and innovation! Here you’ll find interactive labs, security tips, and real-world solutions aligned with CompTIA Security+ and CySA+ standards. Explore content designed to elevate your understanding of threat detection, incident response, and network defense.


# Social Links
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
- {icon: "fa-brands fa-spotify", name: "Spotify", link: "https://spotify.com"}
- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Cyber Labs <em>Showcase</em> # You can add an 'em' element to highlight text.
  projects_description: I present interactive labs and cybersecurity projects, crafted with precision and aligned to CompTIA Security+ and CySA+ standards. These labs focus on practical skills like threat detection, incident response, and network hardening to secure digital environments.


#-------------------------------
# Testimonials Settings
testimonials:
  enable: true
  testimonials_title: Trusted by <em>Professionals</em> # You can add an 'em' element to highlight text.
  testimonials_description: Join our community of cybersecurity professionals where you can sharpen your skills, defend against evolving threats, and secure a safer digital future.

testimonial-items:
  - name: Amelia Jones
    image: "/images/client-1.jpg"
    designation : Network Engineer
    content : This soc analyst is an expert in his field. His ability to understand the needs of clients and create solutions that satisfy them is astounding.

  - name: Ethan Robinson
    image: "/images/client-2.jpg"
    designation : Blockchain Developer
    content : Ty is a true visionary in the field of cyber security. His ability to think outside the box and push boundaries is what sets him apart from the rest.

  - name: Matthew Garcia
    image: "/images/client-3.jpg"
    designation : IT Support Specialist
    content : I cannot recommend this IT security consultant enough. Their ideas were simple to execute, yet complex enough to substantially improve our security posture.


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest <em>Articles</em> & <em>Publications</em> # You can add an 'em' element to highlight text.
  blog_description: Discover the latest industry news, insights, and trends in a few clicks.


#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Questions? <em>Answers</em>. # You can add an 'em' element to highlight text.
  faq_description: Find solutions to common queries here.

faq_items:
  - title: What are your main areas of expertise in cyber security?
    description: My specialization includes threat detection, incident response, and vulnerability assessment, as well as researching and testing security measures to protect systems and data.

  - title: Can you provide examples of your work?
    description: Yes, on my website, you can find a portfolio showcasing examples of my cybersecurity projects, interactive labs, and certifications aligned with industry standards.

  - title: What is your experience with various hardware and software?
    description: I have extensive experience working with various systems, including network infrastructures, servers, endpoint devices, security software, and hardware solutions.

  - title: What specific tools do you use in your working environment?
    description: In my working environment, I utilize a wide range of cybersecurity tools, including SIEM systems (such as Splunk and ELK Stack), network scanners (like Nmap and Wireshark), vulnerability assessment tools (such as Nessus and OpenVAS), and endpoint security solutions (like CrowdStrike and SentinelOne), to name just a few.

  - title: What certifications and qualifications do you bring to the table?
    description: I hold certifications in Google Cybersecurity, CompTIA Security+, CySA+, Cloud Security, and AWS. In addition, I have a Master's degree in Education, which complements my ability to communicate complex concepts effectively. As a lifelong learner, I am continuously expanding my expertise and look forward to adding more certifications and skills to this growing list.

  - title: How can I contact you to discuss my project?
    description: You can contact me through the contact form on my website or directly via email. I'm always open to new projects and ready to discuss your security needs.


#-------------------------------
# Gallery Settings
gallery:
  enable: true
  gallery_title: A Visual Journey Through <em>My World</em> # You can add an 'em' element to highlight text.
  gallery_description: Step into the world of cybersecurity where every project tells a story. From uncovering vulnerabilities in complex systems to building robust defenses, explore the challenges and innovations that drive my mission to secure the digital landscape.
  gallery_caption:

gallery_images:
  - alt: 'Together'
    url: '/cyberfolio/images/02-1.jpg'
  - alt: 'Lifestyle'
    url: '/cyberfolio/images/02-1.jpg'
  - alt: 'Friends'
    url: '/cyberfolio/images/02-1.jpg'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Subscribe to Our <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Join now and stay ahead in cybersecurity. Because your security matters!
  mailchimp_identifier: github.us10.list-manage.com/subscribe/post?u=21c208292da350e84bd383e0b&id=2adf53acb3

  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: f/xvgojkyv # Add your form_id
  description: Baleon comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: privacy-encrypt # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: G-YX3RPSSSB2 # Add your GA Tracking Id